services:
  - type: web
    name: iptv-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    plan: free
    envVars:
      - key: GAVANGTV_FRONTEND
        value: https://sv1.tieulam1.live/trang-chu
      - key: GAVANGTV_API
        value: https://api.tieulam1.live/api/matches
      - key: HOIQUAN_FRONTEND
        value: https://sv2.hoiquan4.live
      - key: HOIQUAN_API
        value: https://sv.hoiquantv.xyz/api/v1/external
      - key: KHANDAIA_FRONTEND
        value: https://tructiep.khandaia.link
      - key: KHANDAIA_API
        value: https://sv.khandai-a.xyz/api/v1/external
      - key: MATCH_MAX_DURATION
        value: "7200"
